### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by rpominov** [rpominov/static-land#12]
Fantasy Land has a great logo!

![image](https://cloud.githubusercontent.com/assets/825702/17634562/e9679f22-60db-11e6-812c-a4e439b3cad1.png)

We need one too. Anyone with art skills?

**Comment by istarkov** [comment]
![image](https://cloud.githubusercontent.com/assets/5077042/17634801/f64cf286-60dc-11e6-9e78-d32f17f4283a.png)

**Comment by rpominov** [comment]
That looks great, but how is it related to Static Land? 😅

**Comment by istarkov** [comment]
As nobody knows what is `algebraic types` I think there is non zero probability that it's related ;-)

**Comment by istarkov** [comment]
BTW something like this will be better
![image](https://cloud.githubusercontent.com/assets/5077042/17635042/0e919152-60de-11e6-9135-d412f9c4d95c.png)

**Comment by rpominov** [comment]
Hm, the tree made me thinking about graphs, and in turn about category theory. Maybe something category theory related?

![image](https://cloud.githubusercontent.com/assets/825702/17635184/ba2411de-60de-11e6-98fc-3efb8f58a99d.png)

**Comment by rpominov** [comment]
Category theory in JavaScript:

![image](https://cloud.githubusercontent.com/assets/825702/17635307/408206be-60df-11e6-9afd-50199cf52a0e.png)

**Comment by rpominov** [comment]
![image](https://cloud.githubusercontent.com/assets/825702/17639745/0719e15c-60fe-11e6-9db1-e318ed79873d.png)

References composition and category theory. And also kinda wraps all this composition/category stuff into an object literal which is a reference to [Type Objects](https://github.com/rpominov/static-land/blob/master/docs/spec.md#type)

**Comment by rpominov** [comment]
![image](https://cloud.githubusercontent.com/assets/825702/17642676/46e17544-6157-11e6-808e-e5c89c1c935f.png)
