### ISSUE TITLE
Help needed to proofread the spec

### ISSUE THREAD

**Issue by rpominov** [rpominov/static-land#14]
I'm not a native english speaker myself and know that everything I write can be improved (grammar, wording, etc.)

Would really appreciate if someone could proofread the spec and other documents (readme, api ref.)

Feel free to send PRs. Thanks!

**Comment by AFortune** [comment]
Do you still need a proofreader?

**Comment by rpominov** [comment]
Frankly I don't know. There may or may not be grammar mistakes and other problems. If you find one just open a PR, that would be great!
