### ISSUE TITLE
chain signature

### ISSUE THREAD

**Issue by gcanti** [rpominov/static-land#18]
Hello, 

in PureScript and Haskell the signature is

```
bind :: Bind m => (m a, a → m b) → m b
```

while in static land is

```
chain :: Chain m => (a → m b, m a) → m b
```

Is there a particular reason for that? At first sight having `m a` near the `chain` call seems more handy

```js
// current spec
monad.chain((a) => {



  ... long snippet of code ...




}, ma) // <= this is far away from the chain call
```

**Comment by rpominov** [comment]
Hey! Two reasons:

1) To match signature of `map` and `ap`.

```
(  a →   b , f a) → f b
(f(a →   b), f a) → f b
(  a → m b , m a) → m b
```

2) For currying.

```js
const flow = (value, ...fns) => fns.reduce((x, fn) => fn(x), value)

flow(T.of(1),
  T.chain(x => T.of(x + 1)),
  T.chain(x => T.of(x + 2))
) // -> T.of(4)
```

`T` would need to implement Ramda-like curried `chain` for this though. And SL used to require that, but now it just allows currying and don't require it.

**Comment by gcanti** [comment]
Thanks, makes sense.

> SL used to require that, but now it just allows currying and don't require it.

Not sure about that. So if I implement a curried `chain` I'm still SL-compliant? There's no mention in the docs

```
chain :: Chain m => (a → m b) → m a → m b
```

Seems weird for interop though, how could you call another library if you don't know if it's curried or not?

**Comment by rpominov** [comment]
> So if I implement a curried chain I'm still SL-compliant?

Not just curried, but Ramda-like curried, when both `T.chain(f)(a)` and `T.chain(f, a)` work.

**Comment by gcanti** [comment]
I see, thanks for explaining. 

So currently `flow-static-land` is not compliant (I wonder if there is a way to fix that). I guess I'll pick the more sensible choice, the curried one

Thanks again @rpominov

**Comment by rpominov** [comment]
I think `flow-static-land` is compliant. Spec only require that `T.chain(f, a)` works, and it doesn't say anything to disallow `T.chain(f)(a)` to work. But it's up to implementer whether to implement currying or not, spec only requires uncurried signature.

**Comment by gcanti** [comment]
Got it. I don't want to pollute this repo with flow-static-land specific issues, I'll think about this a little bit more and, if it's ok for you, I'll open an issue there mentioning you

**Comment by rpominov** [comment]
Yeah, sure.
