### ISSUE TITLE
@@functional/placeholder support

### ISSUE THREAD

**Issue by rpominov** [rpominov/static-land#2]
See http://ramdajs.com/0.19.1/docs/#__ and https://github.com/ramda/ramda/blob/v0.19.1/src/__.js

**Comment by Avaq** [comment]
Consider implementing placeholders [as described in this gist](https://gist.github.com/Avaq/fcc2bdc99a2a8bc083f7), it's much more useful and predictable.

**Comment by rpominov** [comment]
Thanks I will take a look.Though it would be great to have some standard `curry` function that is used between projects like Ramda and SL. We need a spec for `curry` :joy:

**Comment by rpominov** [comment]
Closing because of #6
