### ISSUE TITLE
Registry of types to simplify writing polymorphic code

### ISSUE THREAD

**Issue by rpominov** [rpominov/static-land#3]
It could look something like this:

``` js
const registry = Registry.create()
const polymorphicMap = registry.map

// we don't have code for Nothing, but it doesn't matter for this example
const Maybe = {
  of(value) {
    return {value, __$$type: 'maybe'}
  },
  map(fn, m) {
    return Maybe.of(fn(m.value))
  },
}

// we pass a type object, 
// and a predicate that can tell whether a value can be handled by this type
registry.addType(Maybe, m => m && m.__$$type === 'maybe')

polymorphicMap(x => x + 1, Maybe.of(41)) // Maybe(42)
```

See also: https://github.com/puffnfresh/bilby.js

**Comment by ccorcos** [comment]
I like it!

**Comment by davidchambers** [comment]
Would you consider naming the special property `'@@type'` rather than `'__$$type'`, for compatibility with [`S.type`][1]?


[1]: http://sanctuary.js.org/#type

**Comment by rpominov** [comment]
This is not a special property. It's just how this particular type decided to implement type detection. The API only accepts a predicate, which can check for `'__$$type'`, use `instanceof` or something else.

I also thought about making this predicate part of type object, e.g.:

```js
const Maybe = {
  of(value) {
    ...
  },
  map(fn, m) {
    ...
  },
  isInstance(m) {
    return m => m && m.__$$type === 'maybe'
  }
}

registry.addType(Maybe)
```

**Comment by rpominov** [comment]
What is cool is that `registry` is also a Static Land type (a dictionary with static methods). Although it can't have methods like `of` or `empty`.

**Comment by rpominov** [comment]
This can be a separate project, btw. If someone needs a free idea for a library :)

I actually plan to remove all utils from `static-land` package to separate projects, and leave only specification there eventually. It's just hard to choose what should be in `static-land` and what not, probably the only right solution is to not have any of utils here.

**Comment by polytypic** [comment]
FWIW, if I understand the idea correctly, then I've created mutable registries like this (for convenience to avoid explicit parameter passing) a few times in my career and they've always caused problems at some point.  They can work under special circumstances, such as when you are the only programmer using the registry or when the registry is only used inside a single module and no details of things in the registry leak outside of the module, but such circumstances tend to change.

Instead of using shared mutable state, I would advice using explicit referentially transparent parameter passing.  To reduce the burden of explicitly passing parameters, you can, for example, group multiple parameters into a single dictionary, an immutable registry, of parameters (you have a family of functions that all take a similar bundle of concepts) and, conversely, you can also float parameters upwards and return a dictionary of results (you have a parameterized module, functor in ML parlance, of definitions that depend on a bundle of concepts).

**Comment by rpominov** [comment]
I also have mixed feelings about this. But I think depending on how we use that registry it can be treated not like a mutable state, but rather like an immutable registry. If we split program in two parts: definitions and actual program that does something. And make sure that all definitions are interpreted _before_ actual program, and that all `registry.addType()` calls live in the definitions section, then this registry is kinda immutable.

**Comment by rpominov** [comment]
Just a thought I want to write down:

In cases when Type Object is related to a parametric type (almost always), it might make sense for predicates (or `isInstance` methods) to also accept predicates for inner values. For example:

```js
const List = {
  of(x) {
    return [x]
  },
  map(fn, arr) {
    return arr.map(fn)
  },
  isInstance(pred, arr) {
    return Array.isArray(arr) && arr.every(pred)
  }
}

function isListOfNumbers(arr) {
  return List.isInstance(Number.isFinite, arr)
}
```

**Comment by davidchambers** [comment]
That'd be a good start, @rpominov, but it wouldn't handle types such as `Array a`.

**Comment by rpominov** [comment]
Do you mean when `a` is an arbitrary type? I think it can be arbitrary before we execute the program, but when we actually run it, `a` corresponds to a concrete type and we can have a predicate for it at runtime. But yeah, we would have to pass around predicates. Although if these predicates will be attached to type objects (the `isInstance` method), and we already pass around type objects, then everything should come together I think.

**Comment by rpominov** [comment]
Although I didn't really thought through how these predicates that take other predicates would work with the registry. When I wrote original comment I was focusing on the `isInstance` method actually and how it could work with pattern matching. Maybe this issue actually was a bit wrong place to write it, since it's focused on the registry and not `isInstance` method.

**Comment by rpominov** [comment]
Closing because this is not gonna happen as part of this repository. I think this repo should contain only the specification itself and not any utilities. Utilities should live in separate repos / npm packages. I've already moved [fantasy-to-static](https://github.com/rpominov/fantasy-to-static) to own repo.
