### ISSUE TITLE
Static Land vs FL args order

### ISSUE THREAD

**Issue by rickmed** [rpominov/static-land#39]
eg, apply. Does it needs to be updated? Does static-land and FL aims to share args order?

**Comment by rpominov** [comment]
The order difference is by design. It's optimized for currying. It's very consistent though, basically FL's target value (on which the method is called) goes to the last position in SL's arguments.

```js
a.map(f)
T.map(f, a)

a.ap(f)
T.ap(f, a)

a.chain(f)
T.chain(f, a)
```

**Comment by rickmed** [comment]
@rpominov Obviously! I got confused for a moment -sorry for the noise.

**Comment by rpominov** [comment]
No problem 🙂
