### ISSUE TITLE
Comonad/Extend implementation

### ISSUE THREAD

**Issue by TrySound** [rpominov/static-land#42]
In fantasy land `Extend` implements `Functor`, in static land `Extend` is by itself and `Comonad` implements both `Functor` and `Extend`.
Just would like to figure out who is more right :)

**Comment by rpominov** [comment]
Seems like it changed in Fantasy Land in this commit https://github.com/fantasyland/fantasy-land/commit/11860a59203037b89917e7db7ade37022c2d465c

Not sure yet why, but I'll probably update it here to align with Fantasy Land. 

In general Fantasy Land is the primary source of truth.

**Comment by rpominov** [comment]
Fixed by #43
