### ISSUE TITLE
Add Semigroupoid, Category, Group

### ISSUE THREAD

**Issue by rpominov** [rpominov/static-land#44]
These algebras were added to Fantasy Land, we need to add them too.
This issue is more like a reminder for me, but if anyone wants to submit a PR, please do.

**Comment by masaeedu** [comment]
@rpominov Is there any way we could change the process a bit so that there is some common type metadata representation that both the fantasy-land and static-land specs could be generated from? That way you wouldn't constantly have to play catch up.

**Comment by rpominov** [comment]
Sounds like something complicated and would require a lot of collaboration with Fantasy Land. I'd rather just do it manually.

Don't worry I'll do this soon. It's rather easy, I just didn't have enough motivation. I thought nobody cares about this project anyway. But hey, now I know that at lest you care 😄
